### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by milindgoel15**

### CODE REVIEW

**Review by Frontesque — CHANGES_REQUESTED** [review]
I can't really say that I can suggest people to use winget to install the project.

Idealy, the developer name shouldn't be `Front` either as it's pretty generic. It should really be switched to `Frontesque` if possible as that is my online handle.

The whole winget thing just seems to be more of a hastle than something that I would like to support.

**Review by Frontesque — CHANGES_REQUESTED** [review]
I can't really say that I can suggest people to use winget to install the project.

Idealy, the developer name shouldn't be `Front` either as it's pretty generic. It should really be switched to `Frontesque` if possible as that is my online handle.

The whole winget thing just seems to be more of a hastle than something that I would like to support.

**Comment by Frontesque** [comment]
> You can declare winget installation as optional or as community provided method(this would be better ig).

I'm all for this, but if it's a community supported method, I don't think that it should be included in the readme.

**Comment by milindgoel15** [comment]
Giving users some alternative methods for installation is always good to have, even if it's a community provided.

It's your choice totally. You can decide to close this pr or merge it with "Community Provided Method" tag

**Review by Frontesque — APPROVED** [review]

**Comment by Frontesque** [comment]
> Also, regarding this, since your package is licensed under "Front" name and your package.json also mentions Front in author, probably that's why winget defaulted to that name or the guy who created the first manifest file, used those names

yea I was lazy when making the package.json because I wasn't expecting it to become as popular as it has. I should update that

**Pull request merged**
